### ISSUE TITLE
[feat] 생성 Q10View

### ISSUE THREAD

**Issue by Henrykim1111** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#10]
## ✍️ Description
Question 9 (취미 이상형 월드컵) 뷰 구현 

## ⚒️ Todo
- [x] 팝업창 # 1
- [x] 팝업창 # 2
- [x] 팝업창 # 1 에서 # 2 로 연결
- [x] 8개의 카드와 글씨 (카드 안에는 일러스트)
- [x] 2개 카드 중 1개 카드 누르면 선택받고 저장하기 
- [x] 8개 중 2개씩 나와서 8강 진행
- [x] 선택받은 4개 중 2개씩 4강 진행
- [x] 마지막 2개로 결승전 진행
- [x] 한개 선택할 시 애니메이션 : 선택안된거 투명도 0으로 낮추기
- [x] 8강, 4강, 결승전 진행상황 알려주기
- [x] 최종 결과 저장하기

// 후순위
- [ ] 우승결과 애니메이션
- [ ] 선택된 1개 애니메이션

## ⚙️ ETC
후순위는 여유가 있으면 구현

**Comment by abovocado** [comment]
메인에 추가 완료
