### ISSUE TITLE
[feat] 생성 Q12View

### ISSUE THREAD

**Issue by juwonleee** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#11]
## ✍️ Description
Question 11 (호칭) 뷰 구현

## ⚒️ Todo
- [x] 테이블 생성
- [x] 테이블에 입력받기
- [x] 테이블 열 수정 가능하게 하기
- [x] 테이블 입력 후 저장
- [x] 저장된 테이블 보여주기
- [x] 저장된 테이블에서 하트 누르고 하트 채워지기
- [x] 결과 저장하기

**Comment by abovocado** [comment]
메인에 추가 완료

**Comment by abovocado** [comment]
메인에 추가 완료
