### ISSUE TITLE
 [feat] 생성 Q4View

### ISSUE THREAD

**Issue by abovocado** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#14]
## ✍️ Description
Q4 View를 구현합니다. w/ MK, Lily

## ⚒️ Todo
- [x] Struct Question( ) 추가 및 String 전달
- [x] 묘비 일러스트 삽입
- [x] TextField overlay
- [x] StoreButtonView() 추가
- [x] TextEditor 크기 조절
- [x] 답변 채워지면 Button에 Active 인자 전달
- [x] 저장하기 버튼 누르면 MainView로 NavigationLink 되는 것 확인

## ⚙️ ETC
기타사항
추후 답변을 FileManager에 저장하기 필요
MainView로 넘어갔을 때 카드 뒤집기 필요
