### ISSUE TITLE
[feat] 추가 Q7 View

### ISSUE THREAD

**Issue by dimazsr** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#18]
## ✍️ Description
Question 7. 추억을 떠올리게 하는 음식 적기

## ⚒️ Todo
- [x] View 시작하자마자 키보드 올라오게 하기
- [x] 텍스트 입력 뷰 만들기
- [x] 텍스트 입력 시, 버튼 활성화 되게 하기
- [x] 저장하기 버튼 누르면 MainView 연결하기

## ⚙️ ETC
추후 데이터 저장 필요
추후 MainView 가면 카드 뒤집어지기 필요
