### ISSUE TITLE
[feat] 추가 Q6 View

### ISSUE THREAD

**Issue by dimazsr** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#23]
## ✍️ Description
Question 6. 고치고 싶은 습관 적고 지워보기

## ⚒️ Todo
- [x] View 시작하자마자 키보드 올라오게 하기
- [x] 텍스트 입력 VIew 만들기
- [x] 텍스트 입력 시, 버튼 활성화 되게 하기
- [x] 저장하기 버튼 누르면 모달 창 나오게 하기
- [x] 모달 창 제작하기
- [x] 모달 창 확인 버튼 누르면 문지르는View 연결하기
- [x] 텍스트 문지르면 배경색과 같은 펜으로 그려져 사라지는 것처럼 보이게 하기
- [x] 텍스트 문지르면 버튼 활성화 되게 하기
- [ ] 완료 버튼 누르면 MainView 연결하기

## ⚙️ ETC
추후 데이터 저장 필요
추후 MainView 가면 카드 뒤집어지기 필요
