### ISSUE TITLE
[feat] 추가 Q8 View

### ISSUE THREAD

**Issue by dimazsr** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#28]
## ✍️ Description
Question 8. 지금 당장 떠나고 싶은 곳

## ⚒️ Todo
- [x] 모달 창 띄우기
- [x] 카드 구현하기
- [x] 카드 옆으로 넘기면 방향에 따라 색 바뀌게 하기
- [x] 카드 옆으로 넘기면 값 저장되어 다음 카드 나타나게 하기
- [x]  완료 버튼 누르면 MainView 연결하기

## ⚙️ ETC
추후 데이터 저장 필요
추후 MainView 가면 카드 뒤집어지기 필요

**Comment by abovocado** [comment]
메인에 추가 완료
