### ISSUE TITLE
[feat] 생성 Q11 View

### ISSUE THREAD

**Issue by Henrykim1111** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#29]
## ✍️ Description
Question 11. 인생그래프 그리기 뷰 생성

## ⚒️ Todo
- [x] 모달 창
- [x] 그래프 그리기 - 사진으로 넣기
- [x] 그래프에서 각각 요소들에 슬라이더 배치
- [x] 각각 요소들 선으로 잇기
- [x] 슬라이더 옮기면서 생기는 변화들을 선이 추적해 따라가기
- [x] 최종 결과 저장

## ⚙️ ETC
바쁘다 바빠 현대사회

**Comment by abovocado** [comment]
메인에 추가 완료
