### ISSUE TITLE
[feat] 추가 ReportView

### ISSUE THREAD

**Issue by geee3** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#31]
## ✍️ Description
ReportView: 응답을 통해 보고서 생성

## ⚒️ Todo
- [ ] chatgpt api key 생성
- [ ] chatgpt encoder, decoder 구현
- [ ] api post, get request 구현

## ⚙️ ETC
드디어 끝이 보이는것 같기도 하고,,
