### ISSUE TITLE
[feat] 수정 Q6 & Q9View

### ISSUE THREAD

**Issue by dimazsr** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#46]
## ✍️ Description
Q6 & Q9 버그 수정

## ⚒️ Todo
- [ ] Q6View 습관 적으면 저장하기 버튼 색 안 변함 (버그)
- [ ] Q6View 저장하고 완료된 값 보이게 하기
- [x] Q9View 그릴 때 화면 나옴 (버그)
- [ ] Q9View 저장하고 MainView로 넘어가기
- [ ] Q9View 완성하고 저장된 값 보여주기

## ⚙️ ETC
-

**Comment by dimazsr** [comment]
& 특수문자 사용 불가 이슈로 이슈 닫게됨
