### ISSUE TITLE
[bug] 수정 Q9View

### ISSUE THREAD

**Issue by dimazsr** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#49]
## ✍️ Description
Q9 버그

## ⚒️ Todo
- [x] Q9View 그릴 때 화면 나옴
- [x] Q9View 저장하고 MainView로 넘어가기
- [x] Q9View 완성하고 저장된 값 보여주기

## ⚙️ ETC
-

**Comment by abovocado** [comment]
메인에 추가 완료
