### ISSUE TITLE
[] 수정 최종 수정

### ISSUE THREAD

**Issue by abovocado** [DeveloperAcademy-POSTECH/MC2-Team15-Jihwaja#72]
## ✍️ Description
피드백 및 마지막 시뮬레이션 이후 수정해야 할 사항들을 모두 수정합니다. (결과 뷰 제외)

## ⚒️ Todo
- [ ]  결과지뷰 레이아웃 다시 (+ 글자 키우기)
- [ ]  전체적인 워딩 수정
- [ ]  12번 뷰 수정(색)
- [ ]  카드 뷰 색(빨강, 초록) 더 진하게
- [ ]  퍼센테지 위로 올리기

## ⚙️ ETC
기타사항
